server:
  port: 8080
  
spring:
  application:
    name: rivers-gateway-service
  cloud:
    gateway:
      routes:
        - id: rivers-transaction-service
          uri:  lb://rivers-transaction-service
          predicates:
            - Path=/api/v1/transaction/**
        - id: rivers-account-service
          uri:  lb://rivers-account-service
          predicates:
            - Path=/api/v1/account/**
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:  http://localhost:8761/eureka/   
