server:
  port: 8080
  
spring:
  application:
    name: threerivers-gateway-service
  cloud:
    gateway:
      routes:
        - id: threerivers-transaction-service
          uri:  lb://threerivers-transaction-service
          predicates:
            - Path=/api/v1/transaction/**
        - id: threerivers-account-service
          uri:  lb://threerivers-account-service
          predicates:
            - Path=/api/v1/account/**
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:  http://localhost:8761/eureka/
